name: PR Testing

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  handle-syncwith:
    name: Call Reusable SyncWith Handler
    uses: NilFoundation/ci-cd/.github/workflows/reusable-handle-syncwith.yml@consistent-testing
    with:
      ci-cd-ref: ''
    secrets: inherit

  matrix-test:
    name: Call Reusable Crypto3 Testing
    needs:
      - handle-syncwith
    uses: NilFoundation/ci-cd/.github/workflows/reusable-crypto3-testing.yml@consistent-testing
    with:
      submodules-refs: ${{ needs.handle-syncwith.outputs.prs-shas }}
    secrets: inherit
